version: '3'
services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=classting
      - MYSQL_USER=classting
      - MYSQL_PASSWORD=112233
      - MYSQL_ROOT_PASSWORD=112233
